---
version: "2.0"

services:
  grok-1:
    image: dpemba/grok-1:latest
    expose:
      - port: 8000
        as: 80
        to:
          - global: true

profiles:
  compute:
    grok-1:
      resources:
        cpu:
          units: 8
        memory:
          size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: v100
                - model: h100
                - model: a100
                - model: a40
                - model: a16
                - model: t4
                - model: rtx5000
                - model: rtx6000
                - model: a4000
                - model: a5000
                - model: a6000
                - model: 3090
                - model: 3090ti
                - model: 4090
        storage:
          - size: 200Gi
  placement:
    akash:
      pricing:
        grok-1: 
          denom: uakt
          amount: 100000

deployment:
  grok-1:
    akash:
      profile: grok-1
      count: 1
